export const PLACE_ALIASES = {
  "Tran Phu promenade": "Tran Phu Street Nha Trang",
  "Tran Phu Beach": "Tran Phu Beach Nha Trang",
  "Da Lat avocado ice cream": "Kem Bo Da Lat",
  KUL: "Kuala Lumpur International Airport",
  CXR: "Cam Ranh International Airport",
  DAD: "Da Nang International Airport",
  "Hon Chong rocks": "Hon Chong Promontory Nha Trang",
  "Da Lat Market": "Da Lat Market Cho Da Lat",
  "Lumiere Da Lat": "Lumiere Light Gardens Dalat",
  "Lam Vien Square": "Lam Vien Square Da Lat",
  "Ancient Town": "Hoi An Ancient Town",
  "Japanese Bridge": "Japanese Covered Bridge Hoi An",
  "Non Nuoc": "Non Nuoc Beach Da Nang",
  "My Khe": "My Khe Beach Da Nang",
  "Han River": "Han River Da Nang"
};

export const ALL_PLACE_NAMES = [
  "Kuala Lumpur International Airport",
  "Cam Ranh International Airport",
  "Da Nang International Airport",
  "Tran Phu Street",
  "Thap Ba Mud Bath",
  "I-Resort Mud Bath",
  "Vinpearl Cable Car",
  "VinWonders Nha Trang",
  "Vinpearl Harbour",
  "Vinpearl Resort Nha Trang",
  "Po Nagar Cham Towers",
  "Hon Chong Promontory",
  "Tran Phu promenade",
  "Tran Phu Beach",
  "Nha Trang Bay",
  "Tranh Beach",
  "Hon Tam",
  "Da Lat Market",
  "Da Lat Night Market",
  "Datanla Waterfall",
  "Crazy House",
  "Lumiere Da Lat",
  "Lam Vien Square",
  "Hoi An Ancient Town",
  "Japanese Covered Bridge Hoi An",
  "An Bang Beach",
  "Marble Mountains",
  "Non Nuoc",
  "My Khe Beach",
  "Han River",
  "Dragon Bridge",
  "Han Market Da Nang",
  "Quan Hai San Thai Lai",
  "Lac Canh Beef Restaurant",
  "Bun Ca Nha Trang",
  "VinWonders food court",
  "Banh Trang Nuong Da Lat",
  "Lau Ga La E Da Lat",
  "Da Lat avocado ice cream",
  "Da Lat coffee roastery",
  "Banh Mi Xiu Mai Da Lat",
  "Cao Lau Hoi An",
  "Banh Mi Phuong",
  "Mi Quang Da Nang",
  "Bep Cuon Da Nang",
  "Banh Mi Da Nang",
  "Vietnamese coffee Da Nang",
  "Liberty Central Nha Trang Hotel",
  "Libra Hotel Nha Trang",
  "Le's Cham Hotel Nha Trang",
  "Tran Vien Dong Hotel",
  "Hôtel Colline",
  "Hana Dalat Hotel",
  "Du Parc Hotel Dalat",
  "Mercure Dalat Resort",
  "Park Hotel Dalat",
  "Sandals Mimosa",
  "Hoi An Historic Hotel",
  "Silkotel Hoi An",
  "Chillax Old Town Villa",
  "Stella Maris Beach Danang",
  "Nhat Minh Hotel and Apartment",
  "Sanouva Danang Hotel",
  "Nha Trang",
  "Da Lat",
  "Hoi An",
  "Da Nang",
  "Cam Ranh",
  "KUL",
  "CXR",
  "DAD",
  "Hon Chong rocks",
  "Ancient Town",
  "Japanese Bridge",
  "My Khe",
  "Non Nuoc"
].sort((a, b) => b.length - a.length);

export function googleUrl(kind, place) {
  const query = encodeURIComponent(PLACE_ALIASES[place] || place);
  if (kind === "images") return `https://www.google.com/search?tbm=isch&q=${query}`;
  if (kind === "reviews") return `https://www.google.com/maps/search/${query}+reviews`;
  return `https://www.google.com/search?q=${query}`;
}

export const CITY_THEME = {
  "Nha Trang": "sea",
  "Da Lat": "pine",
  "Hoi An": "lantern",
  "Da Nang": "city"
};

export const DAY_SHORT = ["Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
